
server:
  port: 8003
  error:
    include-stacktrace: never
  servlet:
    session:
      timeout: 600

spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: public
  sql:
    init:
      mode: always
      platform: postgres

  data:
    redis:
      repositories:
        enabled: true

logging:
  level:
    root: INFO
    org:
      springframework: INFO
      hibernate:
        SQL: info
